name = "webjam-2025"

main = ".worker-next/index.mjs"
compatibility_date = "2025-10-16"
compatibility_flags = ["nodejs_compat"]

assets = { directory = ".worker-next/assets", binding = "ASSETS" }

workers_dev = false
routes = [
  { pattern = "webjam.icssc.club", custom_domain = true },
  { pattern = "webjam-2025.icssc.club", custom_domain = true },
  { pattern = "2025.webjam.icssc.club", custom_domain = true },
]